"""创建供货商、进货单、进货明细和库存批次表。

Revision ID: 20260907_0006
Revises: 20260905_0005
Create Date: 2026-09-07 19:57:24.376105

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "20260907_0006"
down_revision: str | Sequence[str] | None = "20260905_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="供货商主键"),
        sa.Column("supplier_no", sa.String(length=20), nullable=False, comment="供货商编号"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="供货商名称"),
        sa.Column("contact_name", sa.String(length=50), nullable=True, comment="联系人姓名"),
        sa.Column("phone", sa.String(length=30), nullable=True, comment="联系电话"),
        sa.Column("address", sa.String(length=255), nullable=True, comment="供货商地址"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
            comment="是否继续合作",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_supplier_name"),
        sa.UniqueConstraint("supplier_no", name="uq_supplier_supplier_no"),
        comment="供货商表",
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="进货单主键"),
        sa.Column("purchase_no", sa.String(length=30), nullable=False, comment="进货单号"),
        sa.Column("department_id", sa.BigInteger(), nullable=False, comment="进货所属部门ID"),
        sa.Column("created_by", sa.BigInteger(), nullable=False, comment="创建进货单的员工ID"),
        sa.Column("received_by", sa.BigInteger(), nullable=True, comment="签收进货单的员工ID"),
        sa.Column("ordered_at", sa.DateTime(), nullable=False, comment="下单时间"),
        sa.Column("expected_arrival_at", sa.DateTime(), nullable=False, comment="预计到货时间"),
        sa.Column("arrived_at", sa.DateTime(), nullable=True, comment="实际到货入库时间"),
        sa.Column(
            "total_amount", sa.Numeric(precision=12, scale=2), nullable=False, comment="进货总金额"
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "arrived", name="purchase_status", native_enum=False, length=20),
            server_default="pending",
            nullable=False,
            comment="进货单状态",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND received_by IS NULL AND arrived_at IS NULL) "
            "OR (status = 'arrived' AND received_by IS NOT NULL "
            "AND arrived_at IS NOT NULL)",
            name="ck_purchase_arrival_fields_match_status",
        ),
        sa.CheckConstraint("status IN ('pending', 'arrived')", name="purchase_status"),
        sa.CheckConstraint(
            "expected_arrival_at > ordered_at", name="ck_purchase_expected_arrival_after_order"
        ),
        sa.CheckConstraint("total_amount >= 0", name="ck_purchase_total_amount_non_negative"),
        sa.ForeignKeyConstraint(["created_by"], ["employee.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["received_by"], ["employee.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purchase_no"),
        comment="进货单表",
        mysql_charset="utf8mb4",
    )
    op.create_index(op.f("ix_purchase_created_by"), "purchase", ["created_by"], unique=False)
    op.create_index(op.f("ix_purchase_department_id"), "purchase", ["department_id"], unique=False)
    op.create_index(
        op.f("ix_purchase_expected_arrival_at"), "purchase", ["expected_arrival_at"], unique=False
    )
    op.create_index(op.f("ix_purchase_ordered_at"), "purchase", ["ordered_at"], unique=False)
    op.create_index(op.f("ix_purchase_received_by"), "purchase", ["received_by"], unique=False)
    op.create_table(
        "purchase_item",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="进货明细主键"
        ),
        sa.Column("purchase_id", sa.BigInteger(), nullable=False, comment="所属进货单ID"),
        sa.Column("product_id", sa.BigInteger(), nullable=False, comment="进货商品ID"),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False, comment="供货商ID"),
        sa.Column(
            "product_no_snapshot",
            sa.String(length=20),
            nullable=False,
            comment="下单时商品编号快照",
        ),
        sa.Column(
            "product_name_snapshot",
            sa.String(length=100),
            nullable=False,
            comment="下单时商品名称快照",
        ),
        sa.Column(
            "supplier_name_snapshot",
            sa.String(length=100),
            nullable=False,
            comment="下单时供货商名称快照",
        ),
        sa.Column("quantity", sa.Integer(), nullable=False, comment="进货数量"),
        sa.Column(
            "unit_cost", sa.Numeric(precision=10, scale=2), nullable=False, comment="本次进货单价"
        ),
        sa.Column(
            "subtotal", sa.Numeric(precision=12, scale=2), nullable=False, comment="进货金额小计"
        ),
        sa.Column("production_date", sa.Date(), nullable=True, comment="生产日期"),
        sa.Column("expiration_date", sa.Date(), nullable=True, comment="到期日期"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.CheckConstraint(
            "expiration_date IS NULL OR production_date IS NULL "
            "OR expiration_date >= production_date",
            name="ck_purchase_item_expiration_after_production",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_purchase_item_quantity_positive"),
        sa.CheckConstraint(
            "subtotal = unit_cost * quantity", name="ck_purchase_item_subtotal_matches"
        ),
        sa.CheckConstraint("unit_cost >= 0", name="ck_purchase_item_unit_cost_non_negative"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purchase_id"], ["purchase.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        comment="进货明细表",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_purchase_item_expiration_date"), "purchase_item", ["expiration_date"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_item_product_id"), "purchase_item", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_item_purchase_id"), "purchase_item", ["purchase_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_item_supplier_id"), "purchase_item", ["supplier_id"], unique=False
    )
    op.create_table(
        "inventory_batch",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="库存批次主键"
        ),
        sa.Column("batch_no", sa.String(length=30), nullable=False, comment="库存批次号"),
        sa.Column("product_id", sa.BigInteger(), nullable=False, comment="商品ID"),
        sa.Column("purchase_item_id", sa.BigInteger(), nullable=False, comment="来源进货明细ID"),
        sa.Column("production_date", sa.Date(), nullable=True, comment="生产日期"),
        sa.Column("expiration_date", sa.Date(), nullable=True, comment="到期日期"),
        sa.Column("initial_quantity", sa.Integer(), nullable=False, comment="到货初始数量"),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False, comment="当前剩余数量"),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "sold_out",
                "discarded",
                name="inventory_batch_status",
                native_enum=False,
                length=20,
            ),
            server_default="available",
            nullable=False,
            comment="库存批次状态",
        ),
        sa.Column("arrived_at", sa.DateTime(), nullable=False, comment="批次到货入库时间"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.CheckConstraint(
            "status IN ('available', 'sold_out', 'discarded')", name="inventory_batch_status"
        ),
        sa.CheckConstraint(
            "expiration_date IS NULL OR production_date IS NULL "
            "OR expiration_date >= production_date",
            name="ck_inventory_batch_expiration_after_production",
        ),
        sa.CheckConstraint("initial_quantity > 0", name="ck_inventory_batch_initial_positive"),
        sa.CheckConstraint(
            "remaining_quantity >= 0 AND remaining_quantity <= initial_quantity",
            name="ck_inventory_batch_remaining_range",
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purchase_item_id"], ["purchase_item.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_no"),
        sa.UniqueConstraint("purchase_item_id"),
        comment="库存批次表",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_inventory_batch_arrived_at"), "inventory_batch", ["arrived_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_batch_expiration_date"),
        "inventory_batch",
        ["expiration_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_batch_product_id"), "inventory_batch", ["product_id"], unique=False
    )
    op.add_column(
        "product",
        sa.Column("shelf_life_days", sa.Integer(), nullable=True, comment="默认保质期天数"),
    )
    op.add_column(
        "product",
        sa.Column("expiry_warning_days", sa.Integer(), nullable=True, comment="临期提前提醒天数"),
    )
    op.create_check_constraint(
        "ck_product_expiry_warning_before_shelf_life",
        "product",
        "shelf_life_days IS NULL OR expiry_warning_days IS NULL "
        "OR expiry_warning_days < shelf_life_days",
    )
    op.create_check_constraint(
        "ck_product_expiry_warning_days_non_negative",
        "product",
        "expiry_warning_days IS NULL OR expiry_warning_days >= 0",
    )
    op.create_check_constraint(
        "ck_product_shelf_life_days_positive",
        "product",
        "shelf_life_days IS NULL OR shelf_life_days > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """撤销 upgrade 中的结构变化。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_product_shelf_life_days_positive", "product", type_="check")
    op.drop_constraint("ck_product_expiry_warning_days_non_negative", "product", type_="check")
    op.drop_constraint("ck_product_expiry_warning_before_shelf_life", "product", type_="check")
    op.drop_column("product", "expiry_warning_days")
    op.drop_column("product", "shelf_life_days")
    op.drop_index(op.f("ix_inventory_batch_product_id"), table_name="inventory_batch")
    op.drop_index(op.f("ix_inventory_batch_expiration_date"), table_name="inventory_batch")
    op.drop_index(op.f("ix_inventory_batch_arrived_at"), table_name="inventory_batch")
    op.drop_table("inventory_batch")
    op.drop_index(op.f("ix_purchase_item_supplier_id"), table_name="purchase_item")
    op.drop_index(op.f("ix_purchase_item_purchase_id"), table_name="purchase_item")
    op.drop_index(op.f("ix_purchase_item_product_id"), table_name="purchase_item")
    op.drop_index(op.f("ix_purchase_item_expiration_date"), table_name="purchase_item")
    op.drop_table("purchase_item")
    op.drop_index(op.f("ix_purchase_received_by"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_ordered_at"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_expected_arrival_at"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_department_id"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_created_by"), table_name="purchase")
    op.drop_table("purchase")
    op.drop_table("supplier")
    # ### end Alembic commands ###
