"""创建商品与供货商关联表。

Revision ID: 20260907_0007
Revises: 20260907_0006
Create Date: 2026-09-07 20:28:07.279874

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "20260907_0007"
down_revision: str | Sequence[str] | None = "20260907_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_supplier",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="商品供货关系主键"
        ),
        sa.Column("product_id", sa.BigInteger(), nullable=False, comment="商品ID"),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False, comment="供货商ID"),
        sa.Column(
            "default_unit_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="默认进货单价",
        ),
        sa.Column(
            "is_preferred",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
            comment="是否为首选供货商",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
            comment="是否仍可供应该商品",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.CheckConstraint(
            "default_unit_cost >= 0", name="ck_product_supplier_default_cost_non_negative"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "supplier_id", name="uq_product_supplier_product_supplier"
        ),
        comment="商品供货商关联表",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_product_supplier_product_id"), "product_supplier", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_supplier_supplier_id"), "product_supplier", ["supplier_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """撤销 upgrade 中的结构变化。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_supplier_supplier_id"), table_name="product_supplier")
    op.drop_index(op.f("ix_product_supplier_product_id"), table_name="product_supplier")
    op.drop_table("product_supplier")
    # ### end Alembic commands ###
