"""add supplier product catalog

Revision ID: 372ffba6f65b
Revises: 20260907_0007
Create Date: 2026-09-07 21:07:56.772155

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "372ffba6f65b"
down_revision: str | Sequence[str] | None = "20260907_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_product",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="供应商商品目录ID"
        ),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False, comment="供应商ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="供应商商品名称"),
        sa.Column(
            "unit_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="当前默认进货单价",
        ),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True, comment="默认保质期天数"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
            comment="是否仍在供应",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.CheckConstraint(
            "shelf_life_days IS NULL OR shelf_life_days > 0",
            name="ck_supplier_product_shelf_life_days_positive",
        ),
        sa.CheckConstraint("unit_cost >= 0", name="ck_supplier_product_unit_cost_non_negative"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "name", name="uq_supplier_product_supplier_name"),
        comment="供应商商品目录表",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_supplier_product_supplier_id"), "supplier_product", ["supplier_id"], unique=False
    )
    op.add_column(
        "product",
        sa.Column(
            "supplier_product_id", sa.BigInteger(), nullable=False, comment="来源供应商商品目录ID"
        ),
    )
    op.create_index(
        op.f("ix_product_supplier_product_id"), "product", ["supplier_product_id"], unique=True
    )
    op.create_foreign_key(
        "fk_product_supplier_product_id",
        "product",
        "supplier_product",
        ["supplier_product_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "purchase_item",
        sa.Column(
            "supplier_product_id", sa.BigInteger(), nullable=False, comment="供应商商品目录ID"
        ),
    )
    op.alter_column(
        "purchase_item",
        "product_id",
        existing_type=mysql.BIGINT(),
        nullable=True,
        comment="签收后生成或匹配的正式商品ID",
        existing_comment="进货商品ID",
    )
    op.alter_column(
        "purchase_item",
        "product_no_snapshot",
        existing_type=mysql.VARCHAR(length=20),
        nullable=True,
        existing_comment="下单时商品编号快照",
    )
    op.create_index(
        op.f("ix_purchase_item_supplier_product_id"),
        "purchase_item",
        ["supplier_product_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_purchase_item_supplier_product_id",
        "purchase_item",
        "supplier_product",
        ["supplier_product_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # 新流程由供应商目录项唯一生成正式商品，旧的多对多关联表不再使用。
    op.drop_table("product_supplier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """撤销 upgrade 中的结构变化。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_supplier",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("default_unit_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_preferred", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_unit_cost >= 0",
            name="ck_product_supplier_default_cost_non_negative",
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "supplier_id",
            name="uq_product_supplier_product_supplier",
        ),
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_product_supplier_product_id"),
        "product_supplier",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_supplier_supplier_id"),
        "product_supplier",
        ["supplier_id"],
        unique=False,
    )
    op.drop_constraint(
        "fk_purchase_item_supplier_product_id",
        "purchase_item",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_purchase_item_supplier_product_id"), table_name="purchase_item")
    op.alter_column(
        "purchase_item",
        "product_no_snapshot",
        existing_type=mysql.VARCHAR(length=20),
        nullable=False,
        existing_comment="下单时商品编号快照",
    )
    op.alter_column(
        "purchase_item",
        "product_id",
        existing_type=mysql.BIGINT(),
        nullable=False,
        comment="进货商品ID",
        existing_comment="签收后生成或匹配的正式商品ID",
    )
    op.drop_column("purchase_item", "supplier_product_id")
    op.drop_constraint("fk_product_supplier_product_id", "product", type_="foreignkey")
    op.drop_index(op.f("ix_product_supplier_product_id"), table_name="product")
    op.drop_column("product", "supplier_product_id")
    op.drop_index(op.f("ix_supplier_product_supplier_id"), table_name="supplier_product")
    op.drop_table("supplier_product")
    # ### end Alembic commands ###
