"""remove product shelf life days

Revision ID: 3878bf50f212
Revises: 372ffba6f65b
Create Date: 2026-09-08 19:40:22.550510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "3878bf50f212"
down_revision: str | Sequence[str] | None = "372ffba6f65b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_product_expiry_warning_before_shelf_life"), "product", type_="check"
    )
    op.drop_constraint(op.f("ck_product_shelf_life_days_positive"), "product", type_="check")
    op.drop_column("product", "shelf_life_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    """撤销 upgrade 中的结构变化。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "shelf_life_days",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="默认保质期天数",
        ),
    )
    op.create_check_constraint(
        op.f("ck_product_shelf_life_days_positive"),
        "product",
        "((`shelf_life_days` is null) or (`shelf_life_days` > 0))",
    )
    op.create_check_constraint(
        op.f("ck_product_expiry_warning_before_shelf_life"),
        "product",
        "((`shelf_life_days` is null) or (`expiry_warning_days` is null) "
        "or (`expiry_warning_days` < `shelf_life_days`))",
    )
    # ### end Alembic commands ###
