"""add daily purchase plans

Revision ID: c453fbf6a0a7
Revises: 428315d374cd
Create Date: 2026-10-04 21:19:34.233328

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "c453fbf6a0a7"
down_revision: str | Sequence[str] | None = "428315d374cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_plan",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="计划主键"),
        sa.Column("department_id", sa.BigInteger(), nullable=False, comment="订货部门"),
        sa.Column("arrival_date", sa.Date(), nullable=False, comment="计划到货日期"),
        sa.Column("quantities", sa.JSON(), nullable=False, comment="商品目录ID对应计划数量"),
        sa.Column("updated_by", sa.BigInteger(), nullable=False, comment="最后修改员工"),
        sa.Column("purchase_id", sa.BigInteger(), nullable=True, comment="自动生成的进货单ID"),
        sa.Column("store_id", sa.BigInteger(), nullable=False, comment="所属门店ID"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purchase_id"),
        sa.UniqueConstraint(
            "store_id", "department_id", "arrival_date", name="uq_purchase_plan_day"
        ),
        comment="每日自动提交订货计划",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        op.f("ix_purchase_plan_arrival_date"), "purchase_plan", ["arrival_date"], unique=False
    )
    op.create_index(op.f("ix_purchase_plan_store_id"), "purchase_plan", ["store_id"], unique=False)


def downgrade() -> None:
    op.drop_table("purchase_plan")
